In [40]:
# pip install yfinance
# pip install lxml

In [59]:
import requests

In [61]:
response = requests.get('https://query1.finance.yahoo.com/v8/finance/chart/MSFT?start=2020-09-26&end=2020-09-27&interval=1h')

In [64]:
response

In [73]:
def get_chart(ticker, start, end, interval):
    url = 'https://query1.finance.yahoo.com/v8/finance/chart/'
    return requests.get(f'{url}{ticker}?start={start}&end={end}&interval={interval}').json()

In [74]:
get_chart('MSFT', start='2020-09-26', end='2020-09-27', interval='1h')

{'chart': {'result': [{'meta': {'currency': 'USD',
     'symbol': 'MSFT',
     'exchangeName': 'NMS',
     'instrumentType': 'EQUITY',
     'firstTradeDate': 511108200,
     'regularMarketTime': 1601492318,
     'gmtoffset': -14400,
     'timezone': 'EDT',
     'exchangeTimezoneName': 'America/New_York',
     'regularMarketPrice': 210.5,
     'chartPreviousClose': 207.26,
     'previousClose': 207.26,
     'scale': 3,
     'priceHint': 2,
     'currentTradingPeriod': {'pre': {'timezone': 'EDT',
       'start': 1601452800,
       'end': 1601472600,
       'gmtoffset': -14400},
      'regular': {'timezone': 'EDT',
       'start': 1601472600,
       'end': 1601496000,
       'gmtoffset': -14400},
      'post': {'timezone': 'EDT',
       'start': 1601496000,
       'end': 1601510400,
       'gmtoffset': -14400}},
     'tradingPeriods': [[{'timezone': 'EDT',
        'start': 1601472600,
        'end': 1601496000,
        'gmtoffset': -14400}]],
     'dataGranularity': '1h',
     'range': '1d',
     'validRanges': ['1d',
      '5d',
      '1mo',
      '3mo',
      '6mo',
      '1y',
      '2y',
      '5y',
      '10y',
      'ytd',
      'max']},
    'timestamp': [1601472600,
     1601476200,
     1601479800,
     1601483400,
     1601487000,
     1601490600,
     1601492318],
    'indicators': {'quote': [{'close': [209.19000244140625,
        211.27000427246094,
        211.8000030517578,
        210.10000610351562,
        211.1699981689453,
        210.30999755859375,
        210.5],
       'high': [209.7899932861328,
        211.3800048828125,
        211.83999633789062,
        211.97999572753906,
        211.9600067138672,
        211.13999938964844,
        210.5],
       'volume': [5415192, 3251258, 25444390, 2397228, 3359240, 1621574, 0],
       'low': [206.5449981689453,
        208.8426971435547,
        210.82000732421875,
        209.9499969482422,
        210.02999877929688,
        209.47000122070312,
        210.5],
       'open': [207.72999572753906,
        209.17999267578125,
        211.27000427246094,
        211.80999755859375,
        210.10000610351562,
        211.13999938964844,
        210.5]}]}}],
  'error': None}}

# https://finance.yahoo.com/world-indices/
# https://pypi.org/project/yfinance/

In [41]:
import yfinance as yf

In [42]:
snp500 = yf.Ticker('^GSPC')

In [46]:
snp500.ticker

'^GSPC'

In [47]:
snp500.history(period='1d', interval='5m')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2020-09-30 09:30:00-04:00,3341.21,3354.07,3340.47,3353.55,40147315,0,0
2020-09-30 09:35:00-04:00,3353.60,3354.11,3346.77,3349.82,41696681,0,0
2020-09-30 09:40:00-04:00,3349.83,3351.13,3347.50,3350.92,58554304,0,0
2020-09-30 09:45:00-04:00,3350.89,3355.88,3349.71,3353.80,37216445,0,0
2020-09-30 09:50:00-04:00,3353.52,3356.58,3352.70,3355.12,40030221,0,0
...,...,...,...,...,...,...,...
2020-09-30 14:20:00-04:00,3389.54,3393.56,3375.89,3377.61,47134306,0,0
2020-09-30 14:25:00-04:00,3377.61,3379.67,3368.04,3377.32,39069958,0,0
2020-09-30 14:30:00-04:00,3377.30,3377.30,3371.31,3372.46,24287878,0,0
2020-09-30 14:35:00-04:00,3372.50,3374.21,3371.65,3373.62,8537734,0,0
2020-09-30 14:37:47-04:00,3372.17,3372.17,3372.17,3372.17,0,0,0

In [48]:
dow_jones = yf.Ticker('^DJI')

In [49]:
dow_jones.history(period='1mo')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-08-31,28643.66,28643.66,28363.55,28430.05,517320000,0,0
2020-09-01,28439.61,28659.26,28290.72,28645.66,423410000,0,0
2020-09-02,28736.79,29162.88,28713.53,29100.50,539510000,0,0
2020-09-03,29090.70,29199.35,28074.76,28292.73,650080000,0,0
2020-09-04,28341.05,28539.75,27664.68,28133.31,694640000,0,0
2020-09-08,27925.23,27925.23,27464.90,27500.89,580860000,0,0
2020-09-09,27711.71,28206.21,27704.54,27940.47,460590000,0,0
2020-09-10,28022.51,28174.78,27447.08,27534.58,442850000,0,0
2020-09-11,27613.86,27828.82,27448.15,27665.64,435330000,0,0
2020-09-14,27718.74,28086.06,27718.74,27993.33,380750000,0,0
2020-09-15,28139.76,28231.06,27931.45,27995.60,414520000,0,0
2020-09-16,28031.69,28364.77,28021.67,28032.38,416650000,0,0
2020-09-17,27834.18,28056.79,27647.93,27901.98,437230000,0,0
2020-09-18,27864.87,27946.69,27487.97,27657.42,698710000,0,0
2020-09-21,27484.71,27484.71,26715.15,27147.70,523660000,0,0
2020-09-22,27170.34,27333.09,26989.93,27288.18,420720000,0,0
2020-09-23,27413.60,27464.46,26716.12,26763.13,459470000,0,0
2020-09-24,26716.09,27094.85,26537.01,26815.44,447810000,0,0
2020-09-25,26694.51,27239.29,26635.38,27173.96,388900000,0,0
2020-09-28,27362.14,27722.60,27362.14,27584.06,401860000,0,0
2020-09-29,27560.24,27605.60,27338.09,27452.66,303820000,0,0
2020-09-30,27514.64,28026.33,27511.06,27832.19,257112175,0,0

In [50]:
nasdaq = yf.Ticker('^IXIC')

In [51]:
nasdaq.history(period='max')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1971-02-05,100.00,100.00,100.00,100.00,0,0,0
1971-02-08,100.84,100.84,100.84,100.84,0,0,0
1971-02-09,100.76,100.76,100.76,100.76,0,0,0
1971-02-10,100.69,100.69,100.69,100.69,0,0,0
1971-02-11,101.45,101.45,101.45,101.45,0,0,0
...,...,...,...,...,...,...,...
2020-09-24,10551.02,10799.55,10520.22,10672.27,4080730000,0,0
2020-09-25,10680.46,10939.55,10639.98,10913.56,3767230000,0,0
2020-09-28,11084.38,11120.79,11019.14,11117.53,3562900000,0,0
2020-09-29,11109.00,11153.23,11065.63,11085.25,3363870000,0,0
2020-09-30,11092.90,11277.96,11092.90,11214.13,2611393075,0,0

In [77]:
import yfinance as yf
msft = yf.Ticker("MSFT")
msft.history(period='1d', interval='1h')

              Open    High     Low   Close    Volume  Dividends  Stock Splits
Date
2020-09-30  207.73  209.79  206.54  209.19   5415192          0             0
2020-09-30  209.18  211.38  208.84  211.27   3251258          0             0
2020-09-30  211.27  211.84  210.82  211.80  25444390          0             0
2020-09-30  211.81  211.98  209.95  210.10   2397228          0             0
2020-09-30  210.10  211.96  210.03  211.17   3359240          0             0
2020-09-30  211.14  211.14  209.47  210.70   1790929          0             0
2020-09-30  210.65  210.65  210.65  210.65         0          0             0

In [56]:
msft.ticker

'MSFT'

In [57]:
msft.actions

            Dividends  Stock Splits
Date
1987-09-21       0.00           2.0
1990-04-16       0.00           2.0
1991-06-27       0.00           1.5
1992-06-15       0.00           1.5
1994-05-23       0.00           2.0
...               ...           ...
2019-08-14       0.46           0.0
2019-11-20       0.51           0.0
2020-02-19       0.51           0.0
2020-05-20       0.51           0.0
2020-08-19       0.51           0.0

[76 rows x 2 columns]

In [21]:
msft.major_holders

        0                                      1
0   1.42%        % of Shares Held by All Insider
1  74.09%       % of Shares Held by Institutions
2  75.16%        % of Float Held by Institutions
3    4630  Number of Institutions Holding Shares

# Bitcoin

In [78]:
bitcoin = yf.Ticker('BTC-USD')
bitcoin.history(period='1d', interval='1h', start='2020-09-26', end='2020-09-27')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-09-26,10733.72,10748.28,10726.85,10731.01,0,0,0
2020-09-26,10730.19,10746.99,10718.20,10745.85,0,0,0
2020-09-26,10751.76,10776.83,10742.71,10764.53,319203328,0,0
2020-09-26,10758.02,10778.50,10753.28,10758.28,0,0,0
2020-09-26,10756.45,10756.45,10719.56,10727.05,0,0,0
2020-09-26,10727.17,10729.38,10702.70,10705.75,0,0,0
2020-09-26,10705.50,10722.42,10704.61,10714.97,3285155840,0,0
2020-09-26,10716.45,10742.07,10699.48,10742.07,108113920,0,0
2020-09-26,10743.31,10745.18,10720.87,10724.81,0,0,0
2020-09-26,10723.93,10723.93,10697.52,10711.90,0,0,0
2020-09-26,10710.48,10715.05,10696.67,10709.01,0,0,0
2020-09-26,10705.38,10740.22,10702.59,10738.25,0,0,0
2020-09-26,10737.28,10749.34,10727.79,10736.93,0,0,0
2020-09-26,10734.46,10750.72,10714.98,10750.72,0,0,0
2020-09-26,10754.34,10758.54,10745.28,10754.06,0,0,0
2020-09-26,10751.70,10775.28,10743.51,10743.51,0,0,0
2020-09-26,10745.90,10745.90,10731.21,10732.04,0,0,0
2020-09-26,10732.24,10738.42,10725.66,10732.56,0,0,0
2020-09-26,10735.41,10765.18,10734.64,10756.60,145242112,0,0
2020-09-26,10750.64,10756.12,10737.74,10756.12,0,0,0
2020-09-27,10753.86,10762.62,10748.91,10752.94,75567104,0,0
2020-09-27,10750.87,10781.33,10743.44,10781.33,186318848,0,0
2020-09-27,10781.19,10804.73,10779.55,10785.11,246710272,0,0
2020-09-27,10788.39,10795.45,10773.51,10788.12,67045376,0,0

In [39]:
bitcoin.ticker

'BTC-USD'

In [14]:
bitcoin.info

{'companyOfficers': [],
 'name': 'Bitcoin',
 'startDate': 1367107200,
 'description': 'The first line of the Bitcoin white paper, written by the anonymous creator Satoshi Nakamoto, reads, “A purely peer-to-peer version of electronic cash, which would allow online payments to be sent directly from one party to another without going through a financial institution.” Bitcoin launched on Jan. 3, 2009, launching the cryptocurrency revolution. Bitcoin is a purely decentralized digital currency, confirming transactions on its own blockchain, which makes it unlike any other asset that came before it.',
 'maxAge': 1,
 'previousClose': 10696.991,
 'regularMarketOpen': 10696.991,
 'twoHundredDayAverage': 9229.525,
 'trailingAnnualDividendYield': None,
 'payoutRatio': None,
 'volume24Hr': 17981894656,
 'regularMarketDayHigh': 10828.821,
 'navPrice': None,
 'averageDailyVolume10Day': 26247103629,
 'totalAssets': None,
 'regularMarketPreviousClose': 10696.991,
 'fiftyDayAverage': 11167.005,
 'trailingAnnualDividendRate': None,
 'open': 10696.991,
 'toCurrency': 'USD=X',
 'averageVolume10days': 26247103629,
 'expireDate': None,
 'yield': None,
 'algorithm': None,
 'dividendRate': None,
 'exDividendDate': None,
 'beta': None,
 'circulatingSupply': 18500780,
 'regularMarketDayLow': 10657.246,
 'priceHint': 2,
 'currency': 'USD',
 'regularMarketVolume': 17981894656,
 'lastMarket': 'CoinMarketCap',
 'maxSupply': None,
 'openInterest': None,
 'marketCap': 198490816512,
 'volumeAllCurrencies': 17981894656,
 'strikePrice': None,
 'averageVolume': 23176948029,
 'priceToSalesTrailing12Months': None,
 'dayLow': 10657.246,
 'ask': None,
 'ytdReturn': None,
 'askSize': None,
 'volume': 17981894656,
 'fiftyTwoWeekHigh': 12359.057,
 'forwardPE': None,
 'fromCurrency': 'BTC',
 'fiveYearAvgDividendYield': None,
 'fiftyTwoWeekLow': 4106.981,
 'bid': None,
 'tradeable': False,
 'dividendYield': None,
 'bidSize': None,
 'dayHigh': 10828.821,
 'exchange': 'CCC',
 'shortName': 'Bitcoin USD',
 'exchangeTimezoneName': 'Europe/London',
 'exchangeTimezoneShortName': 'BST',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '3600000',
 'quoteType': 'CRYPTOCURRENCY',
 'symbol': 'BTC-USD',
 'messageBoardId': 'finmb_BTC_CCC',
 'market': 'ccc_market',
 'regularMarketPrice': 10696.991,
 'logo_url': ''}