In [13]:
# pip install yfinance
# pip install lxml

In [14]:
import requests

In [15]:
headers = requests.utils.default_headers()
headers.update({
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36',    
})

In [16]:
headers

{'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}

In [17]:
requests.post

In [18]:
url = 'https://query1.finance.yahoo.com/v8/finance/chart/MSFT?start=2020-09-26&end=2020-09-27&interval=1h'
response = requests.get(url, headers=headers)

In [20]:
response.json()['chart']['result'][0]['timestamp']

[1639578600,
 1639582200,
 1639585800,
 1639589400,
 1639593000,
 1639596600,
 1639599182]

In [21]:
import datetime

In [22]:
#datetime.datetime.fromtimestamp(1601472600)

In [25]:
def get_ticker(ticker, start, end, interval):
    url = 'https://query1.finance.yahoo.com/v8/finance/chart/'
    return requests.get(f'{url}{ticker}?start={start}&end={end}&interval={interval}', headers=headers).json()

In [26]:
get_ticker('APPL', start='2020-09-27', end='2020-09-28', interval='1m')

{'chart': {'result': [{'meta': {'currency': None,
     'symbol': 'APPL',
     'exchangeName': 'YHD',
     'instrumentType': 'MUTUALFUND',
     'firstTradeDate': None,
     'regularMarketTime': 1561759658,
     'gmtoffset': -18000,
     'timezone': 'EST',
     'exchangeTimezoneName': 'America/New_York',
     'priceHint': 2,
     'currentTradingPeriod': {'pre': {'timezone': 'EST',
       'start': 1639558800,
       'end': 1639578600,
       'gmtoffset': -18000},
      'regular': {'timezone': 'EST',
       'start': 1639578600,
       'end': 1639602000,
       'gmtoffset': -18000},
      'post': {'timezone': 'EST',
       'start': 1639602000,
       'end': 1639616400,
       'gmtoffset': -18000}},
     'dataGranularity': '1d',
     'range': '1d',
     'validRanges': ['1mo',
      '3mo',
      '6mo',
      'ytd',
      '1y',
      '2y',
      '5y',
      '10y',
      'max']},
    'indicators': {'quote': [{}], 'adjclose': [{}]}}],
  'error': None}}

# https://finance.yahoo.com/world-indices/
# https://pypi.org/project/yfinance/

In [1]:
import yfinance as yf

In [30]:
msft = yf.Ticker('MSFT')

In [31]:
msft.ticker

'MSFT'

In [32]:
msft.history(period='1d', interval='1m')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2021-12-15 09:30:00-05:00,328.609985,329.179993,328.049988,329.179993,1518523,0,0
2021-12-15 09:31:00-05:00,329.179993,329.559998,328.655914,328.700012,93965,0,0
2021-12-15 09:32:00-05:00,328.829987,328.989990,327.839996,328.329987,119173,0,0
2021-12-15 09:33:00-05:00,328.359985,329.179993,327.890015,329.089996,77214,0,0
2021-12-15 09:34:00-05:00,328.679993,329.000000,328.619995,328.980011,116555,0,0
...,...,...,...,...,...,...,...
2021-12-15 15:10:00-05:00,330.799988,330.929993,330.519989,330.859985,80089,0,0
2021-12-15 15:11:00-05:00,330.859985,330.959991,330.668091,330.890015,165624,0,0
2021-12-15 15:12:00-05:00,330.859985,330.869995,330.450012,330.459991,87853,0,0
2021-12-15 15:13:00-05:00,330.459991,330.640015,330.350006,330.640015,60590,0,0
2021-12-15 15:14:26-05:00,330.830109,330.830109,330.830109,330.830109,0,0,0

In [35]:
msft.info

{'zip': '98052-6399',
 'sector': 'Technology',
 'fullTimeEmployees': 181000,
 'longBusinessSummary': 'Microsoft Corporation develops, licenses, and supports software, services, devices, and solutions worldwide. Its Productivity and Business Processes segment offers Office, Exchange, SharePoint, Microsoft Teams, Office 365 Security and Compliance, and Skype for Business, as well as related Client Access Licenses (CAL); Skype, Outlook.com, OneDrive, and LinkedIn; and Dynamics 365, a set of cloud-based and on-premises business solutions for organizations and enterprise divisions. Its Intelligent Cloud segment licenses SQL, Windows Servers, Visual Studio, System Center, and related CALs; GitHub that provides a collaboration platform and code hosting service for developers; and Azure, a cloud platform. It also offers support services and Microsoft consulting services to assist customers in developing, deploying, and managing Microsoft server and desktop solutions; and training and certification on Microsoft products. Its More Personal Computing segment provides Windows original equipment manufacturer (OEM) licensing and other non-volume licensing of the Windows operating system; Windows Commercial, such as volume licensing of the Windows operating system, Windows cloud services, and other Windows commercial offerings; patent licensing; Windows Internet of Things; and MSN advertising. It also offers Surface, PC accessories, PCs, tablets, gaming and entertainment consoles, and other devices; Gaming, including Xbox hardware, and Xbox content and services; video games and third-party video game royalties; and Search, including Bing and Microsoft advertising. It sells its products through OEMs, distributors, and resellers; and directly through digital marketplaces, online stores, and retail stores. It has collaborations with Dynatrace, Inc., Morgan Stanley, Micro Focus, WPP plc, ACI Worldwide, Inc., and iCIMS, Inc., as well as strategic relationships with Avaya Holdings Corp. and wejo Limited. Microsoft Corporation was founded in 1975 and is based in Redmond, Washington.',
 'city': 'Redmond',
 'phone': '425 882 8080',
 'state': 'WA',
 'country': 'United States',
 'companyOfficers': [],
 'website': 'https://www.microsoft.com',
 'maxAge': 1,
 'address1': 'One Microsoft Way',
 'industry': 'Software—Infrastructure',
 'ebitdaMargins': 0.48648998,
 'profitMargins': 0.38515,
 'grossMargins': 0.68864995,
 'operatingCashflow': 81945001984,
 'revenueGrowth': 0.22,
 'operatingMargins': 0.42143002,
 'ebitda': 85745000448,
 'targetLowPrice': 299.93,
 'recommendationKey': 'buy',
 'grossProfits': 115856000000,
 'freeCashflow': 49819750400,
 'targetMedianPrice': 364,
 'currentPrice': 331.214,
 'earningsGrowth': 0.489,
 'currentRatio': 2.165,
 'returnOnAssets': 0.14589,
 'numberOfAnalystOpinions': 40,
 'targetMeanPrice': 364.9,
 'debtToEquity': 51.938,
 'returnOnEquity': 0.49303,
 'targetHighPrice': 410,
 'totalCash': 130584002560,
 'totalDebt': 78934999040,
 'totalRevenue': 176250994688,
 'totalCashPerShare': 17.393,
 'financialCurrency': 'USD',
 'revenuePerShare': 23.395,
 'quickRatio': 1.961,
 'recommendationMean': 1.6,
 'exchange': 'NMS',
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EST',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '-18000000',
 'quoteType': 'EQUITY',
 'symbol': 'MSFT',
 'messageBoardId': 'finmb_21835',
 'market': 'us_market',
 'annualHoldingsTurnover': None,
 'enterpriseToRevenue': 13.694,
 'beta3Year': None,
 'enterpriseToEbitda': 28.148,
 '52WeekChange': 0.49735498,
 'morningStarRiskRating': None,
 'forwardEps': 10.53,
 'revenueQuarterlyGrowth': None,
 'sharesOutstanding': 7507979776,
 'fundInceptionDate': None,
 'annualReportExpenseRatio': None,
 'totalAssets': None,
 'bookValue': 20.242,
 'sharesShort': 40876626,
 'sharesPercentSharesOut': 0.0054,
 'fundFamily': None,
 'lastFiscalYearEnd': 1625011200,
 'heldPercentInstitutions': 0.71873003,
 'netIncomeToCommon': 67882999808,
 'trailingEps': 8.939,
 'lastDividendValue': 0.62,
 'SandP52WeekChange': 0.2520609,
 'priceToBook': 16.36271,
 'heldPercentInsiders': 0.00066,
 'nextFiscalYearEnd': 1688083200,
 'yield': None,
 'mostRecentQuarter': 1632960000,
 'shortRatio': 1.68,
 'sharesShortPreviousMonthDate': 1635465600,
 'floatShares': 7500998022,
 'beta': 0.872727,
 'enterpriseValue': 2413521272832,
 'priceHint': 2,
 'threeYearAverageReturn': None,
 'lastSplitDate': 1045526400,
 'lastSplitFactor': '2:1',
 'legalType': None,
 'lastDividendDate': 1637107200,
 'morningStarOverallRating': None,
 'earningsQuarterlyGrowth': 0.476,
 'priceToSalesTrailing12Months': 14.105764,
 'dateShortInterest': 1638230400,
 'pegRatio': 2.16,
 'ytdReturn': None,
 'forwardPE': 31.446821,
 'lastCapGain': None,
 'shortPercentOfFloat': 0.0054,
 'sharesShortPriorMonth': 49332744,
 'impliedSharesOutstanding': None,
 'category': None,
 'fiveYearAverageReturn': None,
 'previousClose': 328.34,
 'regularMarketOpen': 328.61,
 'twoHundredDayAverage': 281.43866,
 'trailingAnnualDividendYield': 0.007004934,
 'payoutRatio': 0.25059998,
 'volume24Hr': None,
 'regularMarketDayHigh': 331.15,
 'navPrice': None,
 'averageDailyVolume10Day': 32527320,
 'regularMarketPreviousClose': 328.34,
 'fiftyDayAverage': 323.5502,
 'trailingAnnualDividendRate': 2.3,
 'open': 328.61,
 'toCurrency': None,
 'averageVolume10days': 32527320,
 'expireDate': None,
 'algorithm': None,
 'dividendRate': 2.48,
 'exDividendDate': 1644969600,
 'circulatingSupply': None,
 'startDate': None,
 'regularMarketDayLow': 324.5,
 'currency': 'USD',
 'trailingPE': 37.043854,
 'regularMarketVolume': 21214127,
 'lastMarket': None,
 'maxSupply': None,
 'openInterest': None,
 'marketCap': 2486155083776,
 'volumeAllCurrencies': None,
 'strikePrice': None,
 'averageVolume': 26331046,
 'dayLow': 324.5,
 'ask': 329.1,
 'askSize': 900,
 'volume': 21214127,
 'fiftyTwoWeekHigh': 349.67,
 'fromCurrency': None,
 'fiveYearAvgDividendYield': 1.42,
 'fiftyTwoWeekLow': 211.94,
 'bid': 329.05,
 'tradeable': False,
 'dividendYield': 0.0076,
 'bidSize': 900,
 'dayHigh': 331.15,
 'regularMarketPrice': 331.135,
 'preMarketPrice': 328.46,
 'logo_url': 'https://logo.clearbit.com/microsoft.com'}

In [36]:
dow_jones = yf.Ticker('^DJI')

In [37]:
dow_jones.history(period='1mo')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-11-15,36128.828125,36236.070312,36031.781250,36087.449219,280660000,0,0
2021-11-16,36076.179688,36316.609375,36076.179688,36142.218750,308290000,0,0
2021-11-17,36159.699219,36159.699219,35909.480469,35931.050781,358310000,0,0
2021-11-18,35901.691406,35952.628906,35654.390625,35870.949219,435080000,0,0
2021-11-19,35879.089844,35879.089844,35555.371094,35601.980469,408840000,0,0
2021-11-22,35631.410156,35929.660156,35615.550781,35619.250000,420810000,0,0
2021-11-23,35619.921875,35841.519531,35542.871094,35813.800781,392520000,0,0
2021-11-24,35752.308594,35825.468750,35591.031250,35804.378906,280960000,0,0
2021-11-26,35366.691406,35366.691406,34749.800781,34899.339844,324580000,0,0
2021-11-29,35017.710938,35287.910156,34895.890625,35135.941406,416040000,0,0
2021-11-30,35056.988281,35056.988281,34424.441406,34483.718750,678800000,0,0
2021-12-01,34678.941406,35004.640625,34006.980469,34022.039062,496000000,0,0
2021-12-02,34076.250000,34759.648438,34076.250000,34639.789062,466900000,0,0
2021-12-03,34692.781250,34801.308594,34264.570312,34580.078125,439550000,0,0
2021-12-06,34633.429688,35356.750000,34633.429688,35227.031250,416720000,0,0
2021-12-07,35423.988281,35819.468750,35423.988281,35719.429688,474940000,0,0
2021-12-08,35716.851562,35840.519531,35602.648438,35754.750000,387650000,0,0
2021-12-09,35722.261719,35864.238281,35577.140625,35754.691406,353020000,0,0
2021-12-10,35830.550781,35982.691406,35710.429688,35970.988281,361200000,0,0
2021-12-13,35958.929688,35958.929688,35609.531250,35650.949219,441110000,0,0
2021-12-14,35605.730469,35779.468750,35441.738281,35544.179688,440900000,0,0
2021-12-15,35549.351562,35772.828125,35389.300781,35772.421875,284046828,0,0

In [38]:
nasdaq = yf.Ticker('^IXIC')

In [39]:
nasdaq.history(period='max')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1971-02-05,100.000000,100.000000,100.000000,100.000000,0,0,0
1971-02-08,100.839996,100.839996,100.839996,100.839996,0,0,0
1971-02-09,100.760002,100.760002,100.760002,100.760002,0,0,0
1971-02-10,100.690002,100.690002,100.690002,100.690002,0,0,0
1971-02-11,101.449997,101.449997,101.449997,101.449997,0,0,0
...,...,...,...,...,...,...,...
2021-12-09,15720.540039,15796.049805,15511.120117,15517.370117,4484230000,0,0
2021-12-10,15629.589844,15677.599609,15477.849609,15630.599609,4395460000,0,0
2021-12-13,15621.269531,15637.059570,15408.250000,15413.280273,4549170000,0,0
2021-12-14,15215.959961,15317.549805,15097.349609,15237.639648,4802460000,0,0
2021-12-15,15230.706055,15432.669922,15055.225586,15432.126953,3318457000,0,0

In [40]:
import yfinance as yf
msft = yf.Ticker("MSFT")
msft.history(period='1d', interval='1h')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
2021-12-15 09:30:00-05:00,328.609985,330.440002,327.799988,329.480103,6002762,0,0
2021-12-15 10:30:00-05:00,329.459991,330.600006,327.329987,327.549988,2515408,0,0
2021-12-15 11:30:00-05:00,327.549988,327.570007,325.640015,326.089996,2742396,0,0
2021-12-15 12:30:00-05:00,326.089996,326.140015,325.280090,325.779999,1872175,0,0
2021-12-15 13:30:00-05:00,325.779999,329.470001,324.500000,327.290009,4450934,0,0
2021-12-15 14:30:00-05:00,327.380005,331.220001,326.899994,331.189606,3553789,0,0
2021-12-15 15:15:38-05:00,331.477600,331.477600,331.477600,331.477600,0,0,0

In [41]:
msft.ticker

'MSFT'

In [42]:
msft.actions

Empty DataFrame
Columns: [Dividends, Stock Splits]
Index: []

In [43]:
msft.major_holders

        0                                      1
0   0.07%        % of Shares Held by All Insider
1  71.87%       % of Shares Held by Institutions
2  71.92%        % of Float Held by Institutions
3    5373  Number of Institutions Holding Shares

# Bitcoin

In [44]:
bitcoin = yf.Ticker('BTC-USD')
bitcoin.history(period='1d', interval='1h', start='2020-09-26', end='2020-09-27')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
2020-09-26 03:00:00+00:00,10733.722656,10748.275391,10726.848633,10731.009766,0,0,0
2020-09-26 04:00:00+00:00,10730.190430,10746.993164,10718.197266,10745.854492,0,0,0
2020-09-26 05:00:00+00:00,10751.759766,10776.826172,10742.712891,10764.533203,319203328,0,0
2020-09-26 06:00:00+00:00,10758.016602,10778.500000,10753.276367,10758.284180,0,0,0
2020-09-26 07:00:00+00:00,10756.454102,10756.454102,10719.564453,10727.047852,0,0,0
2020-09-26 08:00:00+00:00,10727.170898,10729.384766,10702.703125,10705.752930,0,0,0
2020-09-26 09:00:00+00:00,10705.502930,10722.415039,10704.613281,10714.971680,3285155840,0,0
2020-09-26 10:00:00+00:00,10716.451172,10742.065430,10699.475586,10742.065430,108113920,0,0
2020-09-26 11:00:00+00:00,10743.314453,10745.175781,10720.874023,10724.809570,0,0,0
2020-09-26 12:00:00+00:00,10723.931641,10723.931641,10697.519531,10711.904297,0,0,0
2020-09-26 13:00:00+00:00,10710.476562,10715.051758,10696.666992,10709.009766,0,0,0
2020-09-26 14:00:00+00:00,10705.378906,10740.224609,10702.589844,10738.250000,0,0,0
2020-09-26 15:00:00+00:00,10737.279297,10749.343750,10727.794922,10736.934570,0,0,0
2020-09-26 16:00:00+00:00,10734.455078,10750.715820,10714.983398,10750.715820,0,0,0
2020-09-26 17:00:00+00:00,10754.341797,10758.535156,10745.284180,10754.062500,0,0,0
2020-09-26 18:00:00+00:00,10751.697266,10775.278320,10743.507812,10743.507812,0,0,0
2020-09-26 19:00:00+00:00,10745.896484,10745.901367,10731.212891,10732.041992,0,0,0
2020-09-26 20:00:00+00:00,10732.241211,10738.420898,10725.656250,10732.560547,0,0,0
2020-09-26 21:00:00+00:00,10735.411133,10765.175781,10734.642578,10756.595703,145242112,0,0
2020-09-26 22:00:00+00:00,10750.637695,10756.116211,10737.742188,10756.116211,0,0,0
2020-09-27 00:00:00+00:00,10750.869141,10781.334961,10743.438477,10781.334961,186318848,0,0
2020-09-27 01:00:00+00:00,10781.194336,10804.732422,10779.549805,10785.108398,246710272,0,0
2020-09-27 02:00:00+00:00,10788.390625,10795.452148,10773.506836,10788.125000,67045376,0,0

In [45]:
bitcoin.ticker

'BTC-USD'

In [46]:
bitcoin.info

{'companyOfficers': [],
 'name': 'Bitcoin',
 'startDate': 1367107200,
 'description': 'Bitcoin (BTC) is a cryptocurrency . Users are able to generate BTC through the process of mining. Bitcoin has a current supply of 18,882,875. The last known price of Bitcoin is 58,647.26190846 USD and is up 3.81 over the last 24 hours. It is currently trading on 8347 active market(s) with $34,798,046,427.24 traded over the last 24 hours. More information can be found at https://bitcoin.org/.',
 'maxAge': 1,
 'exchange': 'CCC',
 'shortName': 'Bitcoin USD',
 'exchangeTimezoneName': 'UTC',
 'exchangeTimezoneShortName': 'UTC',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '0',
 'quoteType': 'CRYPTOCURRENCY',
 'symbol': 'BTC-USD',
 'messageBoardId': 'finmb_BTC_CCC',
 'market': 'ccc_market',
 'previousClose': 48324.15,
 'regularMarketOpen': 48324.15,
 'twoHundredDayAverage': 46826.27,
 'trailingAnnualDividendYield': None,
 'payoutRatio': None,
 'volume24Hr': 35207249920,
 'regularMarketDayHigh': 5604063,
 'navPrice': None,
 'averageDailyVolume10Day': 31215204554,
 'totalAssets': None,
 'regularMarketPreviousClose': 48324.15,
 'fiftyDayAverage': 57778.76,
 'trailingAnnualDividendRate': None,
 'open': 48324.15,
 'toCurrency': 'USD=X',
 'averageVolume10days': 31215204554,
 'expireDate': None,
 'yield': None,
 'algorithm': None,
 'dividendRate': None,
 'exDividendDate': None,
 'beta': None,
 'circulatingSupply': 18901892,
 'regularMarketDayLow': 46707.92,
 'priceHint': 2,
 'currency': 'USD',
 'regularMarketVolume': 35207249920,
 'lastMarket': 'CoinMarketCap',
 'maxSupply': None,
 'openInterest': None,
 'marketCap': 925733617664,
 'volumeAllCurrencies': 35207249920,
 'strikePrice': None,
 'averageVolume': 35533195139,
 'priceToSalesTrailing12Months': None,
 'dayLow': 46707.92,
 'ask': None,
 'ytdReturn': None,
 'askSize': None,
 'volume': 35207249920,
 'fiftyTwoWeekHigh': 5604063,
 'forwardPE': None,
 'fromCurrency': 'BTC',
 'fiveYearAvgDividendYield': None,
 'fiftyTwoWeekLow': 19298.316,
 'bid': None,
 'tradeable': False,
 'dividendYield': None,
 'bidSize': None,
 'dayHigh': 5604063,
 'regularMarketPrice': 48975.707,
 'preMarketPrice': None,
 'logo_url': ''}